export const PRICES = {
  udaithal: 5,
  house: 10,
  milagai: 30,
  livestock: 3, // cow or goat
};

export type Language = 'en' | 'ta';

export const TRANSLATIONS = {
  en: {
    title: 'Token Manager',
    customerAccess: 'Customer Access',
    adminAccess: 'Admin Access',
    fillDetails: 'Fill Details',
    selectToken: 'Select Token (1-50)',
    enterName: 'Enter Name or Voice',
    selectProducts: 'Select Multiple or Single Product',
    enterKg: 'Enter KG',
    ok: 'OK',
    tracking: 'Tracking Details',
    tokenNumber: 'Token Number',
    name: 'Name',
    productDetails: 'Product Details and KG',
    amount: 'Amount',
    paymentStatus: 'Payment Status',
    workStatus: 'Work Status',
    history: 'History',
    delete: 'Delete',
    pending: 'Pending',
    completed: 'Completed',
    paid: 'Paid',
    unpaid: 'Unpaid',
    password: 'Password',
    login: 'Login',
    allCustomers: 'All Customer Details',
    totalAmount: 'Total Amount',
    currentAndPrevious: 'Current and Previous Amount',
    update: 'Update',
    contact: 'Contact',
    location: 'Location',
    udaithal: 'Udaithal',
    house: 'House',
    milagai: 'Milagai',
    livestock: 'Cow/Goat',
    noRecords: 'No records found',
    searching: 'Searching...',
    voiceStart: 'Speak now...',
    voiceError: 'Voice recognition failed. Please type manually.',
    removeVillage: '',
    previousBalance: 'Previous Balance',
    logOut: 'Log Out',
    lastOrder: 'Last Order',
    editAmount: 'Edit Amount',
    save: 'Save',
    cancel: 'Cancel',
    newAmount: 'New Amount',
    payOnline: 'Pay Online',
    grandTotal: 'Grand Total (Incl. Previous)',
    deleteRestriction: 'Note: Records can only be deleted after work is COMPLETED and PAID.',
    deleted: 'Deleted'
  },
  ta: {
    title: 'டோக்கன் மேலாளர்',
    customerAccess: 'வாடிக்கையாளர் அணுகல்',
    adminAccess: 'நிர்வாகி அணுகல்',
    fillDetails: 'விவரங்களை நிரப்பவும்',
    selectToken: 'டோக்கனைத் தேர்ந்தெடுக்கவும் (1-50)',
    enterName: 'பெயரை உள்ளிடவும் அல்லது பேசவும்',
    selectProducts: 'ஒன்று அல்லது பல பொருட்களைத் தேர்ந்தெடுக்கவும்',
    enterKg: 'கிலோவை உள்ளிடவும்',
    ok: 'சரி',
    tracking: 'கண்காணிப்பு விவரங்கள்',
    tokenNumber: 'டோக்கன் எண்',
    name: 'பெயர்',
    productDetails: 'தயாரிப்பு விவரங்கள் மற்றும் கிலோ',
    amount: 'தொகை',
    paymentStatus: 'கட்டண நிலை',
    workStatus: 'பணி நிலை',
    history: 'வரலாறு',
    delete: 'நீக்கு',
    pending: 'நிலுவையில் உள்ளது',
    completed: 'முடிந்தது',
    paid: 'செலுத்தப்பட்டது',
    unpaid: 'செலுத்தப்படவில்லை',
    password: 'கடவுச்சொல்',
    login: 'உள்நுழைக',
    allCustomers: 'அனைத்து வாடிக்கையாளர் விவரங்கள்',
    totalAmount: 'மொத்த தொகை',
    currentAndPrevious: 'தற்போதைய மற்றும் முந்தைய தொகை',
    update: 'புதுப்பி',
    contact: 'தொடர்பு',
    location: 'இடம்',
    udaithal: 'உடைத்தல்',
    house: 'வீடு',
    milagai: 'மிளகாய்',
    livestock: 'பசு/ஆடு',
    noRecords: 'பதிவுகள் எதுவும் இல்லை',
    searching: 'தேடுகிறது...',
    voiceStart: 'இப்போது பேசுங்கள்...',
    voiceError: 'குரல் அங்கீகாரம் தோல்வியடைந்தது. கைமுறையாக தட்டச்சு செய்யவும்.',
    removeVillage: '',
    previousBalance: 'முந்தைய இருப்பு',
    logOut: 'வெளியேறு',
    lastOrder: 'கடைசி ஆர்டர்',
    editAmount: 'தொகையைத் திருத்தவும்',
    save: 'சேமி',
    cancel: 'ரத்துசெய்',
    newAmount: 'புதிய தொகை',
    payOnline: 'ஆன்லைனில் பணம் செலுத்துங்கள்',
    grandTotal: 'மொத்த தொகை (முந்தையது உட்பட)',
    deleteRestriction: 'குறிப்பு: வேலை முடிந்து பணம் செலுத்திய பின்னரே பதிவுகளை நீக்க முடியும்.',
    deleted: 'நீக்கப்பட்டது'
  },
};
